
package ru.naztrans.elcom.webclientclasses;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CategoryServiceService", targetNamespace = "http://service.elcom.naztrans.ru/", wsdlLocation = "http://localhost:8080/myshop/CategoryService?wsdl")
public class CategoryServiceService
    extends Service
{

    private final static URL CATEGORYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CATEGORYSERVICESERVICE_EXCEPTION;
    private final static QName CATEGORYSERVICESERVICE_QNAME = new QName("http://service.elcom.naztrans.ru/", "CategoryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/myshop/CategoryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATEGORYSERVICESERVICE_WSDL_LOCATION = url;
        CATEGORYSERVICESERVICE_EXCEPTION = e;
    }

    public CategoryServiceService() {
        super(__getWsdlLocation(), CATEGORYSERVICESERVICE_QNAME);
    }

    public CategoryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATEGORYSERVICESERVICE_QNAME, features);
    }

    public CategoryServiceService(URL wsdlLocation) {
        super(wsdlLocation, CATEGORYSERVICESERVICE_QNAME);
    }

    public CategoryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATEGORYSERVICESERVICE_QNAME, features);
    }

    public CategoryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CategoryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CategoryService
     */
    @WebEndpoint(name = "CategoryServicePort")
    public CategoryService getCategoryServicePort() {
        return super.getPort(new QName("http://service.elcom.naztrans.ru/", "CategoryServicePort"), CategoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CategoryService
     */
    @WebEndpoint(name = "CategoryServicePort")
    public CategoryService getCategoryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.elcom.naztrans.ru/", "CategoryServicePort"), CategoryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATEGORYSERVICESERVICE_EXCEPTION!= null) {
            throw CATEGORYSERVICESERVICE_EXCEPTION;
        }
        return CATEGORYSERVICESERVICE_WSDL_LOCATION;
    }

}
